version: '3.3'

services:
  crackhash-manager:
    env_file:
      - docker.env
    build: ./Manager/
    networks:
      - crackhash
    ports:
      - "10010:80"
    restart: on-failure
  crackhash-worker:
    env_file:
      - docker.env
    build: ./Worker/
    networks:
      - crackhash
    restart: on-failure

networks:
  crackhash:
    driver: bridge